version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  
jobs:
  build:
    executor: dk_api
    steps:
      - checkout
      - run: gem install bundler:2.1.4
      - run: bundle install --jobs=4
      - save_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor
  test:
    executor: dk_api
    steps:
      - checkout
      - run: gem install bundler:2.1.4
      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }} 
      - run: ~/project/bin/rake db:create
      - run: ~/project/bin/rake db:migrate
      - run: ~/project/bin/rake db test

executors:
  dk_api:
    docker:
      - image: circleci/ruby:2.6.5-buster
        environment:
          BUNDLE_JOBS: "4"
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

workflows:
  version: 2.1
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
