version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5-buster
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - run: bundle config set path 'vendor/bundle'
      - run: bundle install --jobs=4
      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate
      - run: bundle exec test
